base_radius_m: 0.045
lift_m: 0.065
cam_resolution: 720
crank_rpm: 28.0
cam_drive_ratio: 2.0
spool_core_radius_m: 0.021
spool_width_m: 0.09
thread_diameter_m: 0.00035
thread_density_kg_per_m: 0.00042
traverse_mass_kg: 0.42
spring_k_N_per_m: 55.0
damping_Ns_per_m: 2.1
drive_efficiency: 0.78
spool_drive_ratio: 1.1
sim_cycles: 20
layer_bins: 60
waxed_leather_friction_coeff: 0.12
cam_material_wear_coefficient: 1.5e-08
bobbin_count: 3
safety_factor: 1.6
maximum_human_power_W: 45.0
ambient_temp_C: 22.0
humidity_percent: 55.0
hand_crank_radius_m: 0.18
leather_cord_elasticity: 0.015
thread_target_tension_N: 0.45
