bell_masses_kg: [12.0, 10.5, 9.0, 7.5]
bell_frequencies_hz: [523.25, 466.16, 392.00, 329.63]
striker_mass_kg: 2.5
striker_arm_length_m: 0.45
drum_radius_m: 0.25
rotation_speed_rpm: 12.0
strike_sequence: [0, 1, 2, 3, 1, 0]
timing_noise_std: 0.05
