string_lengths_m: [0.62, 0.59, 0.56]
string_tensions_n: [240.0, 225.0, 210.0]
string_linear_density_kg_per_m: [0.005, 0.0048, 0.0046]
wheel_surface_speed_m_per_s: 0.65
bow_contact_time_s: 0.35
key_velocity_profile: [0.8, 0.6, 0.7, 0.9, 0.75]
note_sequence: [0, 1, 2, 1, 0, 2]
bow_noise_std: 0.05
