wheel_radius_m: 0.22
wheel_width_m: 0.05
drive_gear_teeth: 120
counter_gear_teeth: 12
bucket_capacity: 100
pebbles_per_drop: 1
slip_std_percent: 0.4
calibration_error_percent: 0.2
distance_grid_m: [50, 100, 250, 500, 750, 1000]
