mass_kg: 42.0
wheel_radius_m: 0.18
wheel_inertia: 0.15
drag_coefficient: 0.8
frontal_area_m2: 0.2
spring_k_Nm: 1.0
spring_k_cubic: 0.01
spring_max_theta_rad: 8.0
spring_damping: 0.15
spring_laminations: 8
rolling_coeff: 0.015
bearing_friction: 0.8
gear_efficiency: 0.78
timestep_s: 0.02
duration_s: 30.0
escapement_teeth: 12
escape_angle: 0.5236
escapement_damping: 0.12
target_period: 0.8
