span_length_m: 12.0
load_capacity_kg: 5000.0
rotation_time_limit_s: 120.0
structure_mass_kg: 3200.0
counterweight_tank_volume_m3: 7.5
counterweight_fluid_density_kg_m3: 1000.0
youngs_modulus_pa: 200000000000.0
moment_of_inertia_m4: 0.045
truss_depth_m: 2.6
deck_width_m: 4.0
angle_samples_deg: [0, 15, 30, 45, 60, 75, 90]
gravity_m_s2: 9.80665
safety_factor_target: 3.0
counterweight_arm_fraction: 0.5
load_distribution_factor: 1.0
