title: "The da Vinci Codex"
tagline: "Computational Archaeology of Renaissance Engineering"
description: "Open-source computational framework exploring Leonardo da Vinci's mechanical inventions through modern engineering, physics simulation, and safety analysis."
url: https://shannon-labs.github.io
baseurl: /davinci-codex
permalink: pretty
timezone: UTC

# Contact Information
email: hunter@shannonlabs.dev
twitter_username: huntermbown
github_username: Shannon-Labs
linkedin_username: hunterbown

# Build Settings
markdown: kramdown
highlighter: rouge
theme: null
sass:
  style: compressed
  sass_dir: _sass

# Plugins
plugins:
  - jekyll-github-metadata
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# Collections for better organization
collections:
  inventions:
    output: true
    permalink: /:collection/:name/
  gallery:
    output: true
    permalink: /:collection/:name/
  research:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: default
      author: "Hunter Bown"
  - scope:
      path: ""
      type: "inventions"
    values:
      layout: invention
  - scope:
      path: ""
      type: "gallery"
    values:
      layout: gallery
  - scope:
      path: ""
      type: "research"
    values:
      layout: research

# Exclude from processing
exclude:
  - book/
  - book/_build/
  - README.md
  - overview.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - vendor/bundle/
  - .sass-cache
  - .jekyll-cache
  - .jekyll-metadata
  - gemfiles
  - _site

# Social Media and SEO
social:
  name: Shannon Labs
  links:
    - https://github.com/Shannon-Labs
    - https://twitter.com/huntermbown
    - https://linkedin.com/in/hunterbown

# Renaissance Theme Configuration
renaissance:
  # Color palette inspired by da Vinci's notebooks
  colors:
    primary: "#8B4513"      # Renaissance brown
    secondary: "#DAA520"    # Gold accent
    manuscript: "#F5F5DC"   # Beige parchment
    ink: "#2F4F4F"          # Dark slate gray
    accent: "#CD853F"       # Peru
  
  # Typography inspired by Renaissance manuscripts
  fonts:
    heading: "Cinzel, serif"
    body: "EB Garamond, serif"
    code: "JetBrains Mono, monospace"
  
  # Features
  features:
    search: true
    dark_mode: true
    animations: true
    interactive_demos: true

# Navigation structure
navigation:
  - title: "Home"
    url: /
  - title: "Inventions"
    url: /inventions/
    children:
      - title: "Flight & Motion"
        children:
          - title: "Aerial Screw"
            url: /aerial_screw/
          - title: "3D Viewer"
            url: /aerial_screw_viewer/
          - title: "Ornithopter"
            url: /ornithopter/
          - title: "Parachute"
            url: /parachute/
          - title: "Safety Analysis"
            url: /parachute_safety_dossier/
      - title: "Mechanical Systems"
        children:
          - title: "Self-Propelled Cart"
            url: /self_propelled_cart/
          - title: "3D Viewer"
            url: /self_propelled_cart_viewer/
          - title: "Mechanical Odometer"
            url: /mechanical_odometer/
          - title: "Revolving Bridge"
            url: /revolving_bridge/
          - title: "Armored Walker"
            url: /armored_walker/
          - title: "Variable Pitch Mechanism"
            url: /variable_pitch_mechanism/
          - title: "Programmable Loom"
            url: /programmable_loom/
      - title: "Musical Automata"
        children:
          - title: "Mechanical Lion"
            url: /mechanical_lion/
          - title: "3D Viewer"
            url: /mechanical_lion_viewer/
          - title: "Musical Ensemble"
            url: /mechanical_ensemble/
          - title: "Mechanical Carillon"
            url: /mechanical_carillon/
          - title: "Mechanical Drum"
            url: /mechanical_drum/
          - title: "Mechanical Organ"
            url: /mechanical_organ/
          - title: "Mechanical Trumpeter"
            url: /mechanical_trumpeter/
          - title: "Programmable Flute"
            url: /programmable_flute/
          - title: "Viola Organista"
            url: /viola_organista/
          - title: "3D Collection"
            url: /musical_instruments_viewer/
  - title: "Interactive Features"
    url: /interactive/
    children:
      - title: "Invention Dashboard"
        url: /dashboard/
      - title: "3D Models"
        url: /3d-models/
        children:
          - title: "Aerial Screw Viewer"
            url: /aerial_screw_viewer/
          - title: "Mechanical Lion Viewer"
            url: /mechanical_lion_viewer/
          - title: "Self-Propelled Cart Viewer"
            url: /self_propelled_cart_viewer/
          - title: "Musical Instruments Collection"
            url: /musical_instruments_viewer/
          - title: "Complete Gallery"
            url: /3d-gallery/
      - title: "Interactive Book"
        url: /book/
      - title: "Educational Resources"
        url: /education/
  - title: "Research & Analysis"
    url: /research/
    children:
      - title: "Overview"
        url: /overview/
      - title: "Methodology"
        url: /adaptation_methodology/
      - title: "Cultural Context"
        url: /renaissance_cultural_context/
      - title: "Technical Analysis"
        url: /analysis/
      - title: "Physics Simulations"
        url: /physics/
      - title: "Planning Documents"
        url: /planning/
      - title: "Specifications"
        url: /specifications/
      - title: "Safety & Ethics"
        url: /utilization_overview/
  - title: "Documentation"
    url: /documentation/
    children:
      - title: "Technical Guides"
        url: /3D_VIEWER_DOCUMENTATION/
      - title: "Image Documentation"
        url: /image_documentation/
      - title: "Visual Guides"
        url: /visual_guides/
      - title: "Educational Infographics"
        url: /educational_infographics/
      - title: "Branding Guide"
        url: /BRANDING_GUIDE.md/
      - title: "Testing Documentation"
        url: /TESTING/
      - title: "Maintenance"
        url: /MAINTENANCE.md/
      - title: "Releases"
        url: /releases/
  - title: "GitHub"
    url: https://github.com/Shannon-Labs/davinci-codex

