source 'https://rubygems.org'

gem 'github-pages', group: :jekyll_plugins
gem 'jekyll', '~> 3.9.0'
gem 'kramdown-parser-gfm'

group :jekyll_plugins do
  gem 'jekyll-github-metadata'
  gem 'jekyll-sitemap'
  gem 'jekyll-feed'
  gem 'jekyll-seo-tag'
end

