pipe_lengths_m: [0.45, 0.4, 0.36, 0.32]
pipe_diameters_m: [0.06, 0.055, 0.05, 0.045]
bellows_pressure_kpa: 6.5
wind_chest_volume_l: 12.0
barrel_rotation_rpm: 18.0
note_schedule: [0, 1, 2, 3, 2, 1, 0]
airflow_noise_std: 0.08
